# Numpy(2)
## 데이터 타입

Numpy의 ndarray는 모두 같은 타입의 요소들로 이루어진다. 데이터 타입을 따로 지정하지 않는 경우 타입을 자동으로 선택한다. 아래와 같이 데이터를 명시적으로 선언 할 수도 있다.

In [2]:
import numpy as np

In [5]:
x = np.array([1, 2]) #자동으로 타입 선택 
y = np.array([1.0, 2.0]) #자동으로 타입 선택 
z = np.array([1, 2], dtype =np.int64) #명시적으로 타입을 지정 

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


In [6]:
z = np.array([1, 2], dtype=np.float32)
z

array([1., 2.], dtype=float32)

## 배열 연산

배열에 대한 수학 연산은 기본적으로 요소단위로 이루어지며, 연산자와 함수 둘 다 사용 가능하다:

In [4]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [3,8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [3. 8.]]


In [5]:
#요소 합 , 결과로 ndarray를 생성'
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [ 6. 12.]]
[[ 6.  8.]
 [ 6. 12.]]


In [6]:
#요소 차 
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [ 0. -4.]]
[[-4. -4.]
 [ 0. -4.]]


In [7]:
#요소 곱 
print(x * y)
print(np.multiply(x,y))

[[ 5. 12.]
 [ 9. 32.]]
[[ 5. 12.]
 [ 9. 32.]]


In [8]:
#요소 나눗셈 
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [1.         0.5       ]]
[[0.2        0.33333333]
 [1.         0.5       ]]


In [9]:
# Elementwise square root 
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [10]:
import math 
a-[1, 2, 3,4]

math.sqrt(a) #sqrt()가 리스트에도 적용하는지 확인

NameError: name 'a' is not defined

벡터의 내적은 dot 함수를 사용한다. dot은 numpy 함수와 ndarray의 메소드 두 방식으로 사용이 가능하다. 

In [11]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11,12])

print(x, x.shape)
print(y, y.shape)
print(v, v.shape)
print(w, w.shape)

[[1 2]
 [3 4]] (2, 2)
[[5 6]
 [7 8]] (2, 2)
[ 9 10] (2,)
[11 12] (2,)


In [12]:
# 벡터 내적(Inner product)
print(v.dot(w))
print(np.dot(v, w))

219
219


In [14]:
# 행렬과 벡터 간 곱셈(matrix / vector product)
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [15]:
# 행렬 곱셈(Matrix multiplication / product)
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy 가 제공하는 함수에는 sum 등이 있다.

In [18]:
x = np.array([[1,2],[3,4]])
print(x)

print(np.sum(x)) # 모든 요소들의 합 "10"
print(np.sum(x, axis =0)) #열의 합을 계산
print(np.sum(x, axis=1)) #행의 합을 계산 

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


Numpy의 다른 함수들은 다음을 참조 documentation.

행렬연산에서 중요한 연산 중 하나는 전치행렬(transposed matrix)를 구하는 것이다. 아래와 같이 Numpy의 T 메소드를 이용해서 구한다:

In [20]:
x = np.array([[1,2,3],[4,5,6]])
print(x)
print(x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


## 브로드캐스팅 

브로드캐스팅은 크기가 서로 다른 배열에 대해 연산을 할 경우 사용되는 강력한 메커니즘이다. 
작은 배열이 큰 배열을 대상으로 여러번 연산 할 때 유용하다.

In [27]:
# 벡터 v를 행렬 x의 모든 행에 더하고자함.
# 그 결과는 행렬 y에 저장 
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print('x=\n', x)
v = np.array([1, 0, 1])
y = np.empty_like(x) #x와 동일한 shape를 가진 빈 행렬 생성 
# 반복문을 이용해 x의 각 행에 v를 더함
for i in range(4):
    y[i] = x[i] + v

print('y =\n', y)
print(y.shape)

x=
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
y =
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
(4, 3)


다음으로 생각할 수 있는 방법은 벡터 v를 반복해서 x와 같은 크기로 만들고 vv에 저장한 다음에 x아 vv의 요소합 (elementwise sum)을 하는 것이다:

In [31]:
vv = np.tile(v,(4,1)) # x 행의 수만큼 v를 반복해서 vv를 생성
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [32]:
y = x + vv # x와 vv를 요소합
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy가 제공하는 브로드캐스팅(broadcasting)을 이용하면 쉽게 구현이 가능:

In [33]:
import numpy as np

x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x + v # x와 v의 shape이 다르기 때문에 자동으로 브로드캐스팅이 작동
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


y = x + v에서 x의 shape은 (4, 3) 이고 v의 shape은 (3,) 이므로 브로드캐스팅이 작동, v의 shape가 (4, 3)이 되도록 v를 복사한 후에, 요소합을 구하게 된다.

브로드캐스팅의 동작원칙은 다음과 같다:

1. 만일 두 배열의 차수가 다르면 차수가 적은 배열을 늘려서 shape를 맞춰서 연산을 한다.
2. 이 때 두 배열이 한 차원에서 크기가 동일하거나 다른 쪽의 크기가 1이면 호환가능(compatible)하다.
3. 두 배열이 모든 차원에서 호환가능하면 브로드캐스팅이 된다.
4. 한 배열의 어떤 차원의 크기가 1이고 다른 배열의 같은 차원의 크기가 1보다 크면 큰 쪽에 맞춰서 복사된다.

상세한 내용은 다음을 참조: [documentation](https://numpy.org/doc/stable/user/basics.broadcasting.html)

브로드캐스팅을 지원하는 함수를 universal function이라고 한다. universal function의 모든 리스트는 다음을 참조 : [documentation](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs)

브로드캐스팅의 다른 예제 : 

In [34]:
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) #w has shape(2,)
# 위의 경우, v와 w의 shape이 다르므로 요소곱을 하는 경우 에러가 발생함
# 먼저 v를 열로 바꿔서 shape을 (3, 1)로 만든 후에 브로드캐스팅을 적용하면 v와 w가 (3, 2)로 확장되고
# 그 다음 요소곱을 실행
print(np.reshape(v,(3,1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [35]:
# 벡터를 행렬의 각 행에 더하고자 하는 경우
x = np.array([[1,2,3], [4,5,6]])
print('x =\n', x)
# x는 (2, 3)이고 v는 (3,)이므로 v를 (2, 3)으로 브로드캐스트

print('result =\n', x + v)

x =
 [[1 2 3]
 [4 5 6]]
result =
 [[2 4 6]
 [5 7 9]]


In [36]:
# 벡터를 행렬의 각 행에 더하고자 하는 경우
x = np.array([[1,2,3], [4,5,6]])
print('x =\n', x)
# x는 (2, 3)이고 v는 (3,)이므로 v를 (2, 3)으로 브로드캐스트

print('result =\n', x + v)

x =
 [[1 2 3]
 [4 5 6]]
result =
 [[2 4 6]
 [5 7 9]]


In [37]:
# x 행렬에 상수 곱을 하고 싶을 때
# Numpy는 스칼라(곱하려는값)을  shape ()로 취급;
# 따라서 x에 맞춰 스칼라를 shape (2, 3)으로 브로드캐스팅이 가능
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


In [39]:
x = np.array([[3,4,5],[7,8,9]])
c1 = np.array(2) #c1.shape is ()
c2 = np.array([2]) #c2.shpe is (1,)

print( x*c1 )
print( x*c2 )
print( x *2 )

[[ 6  8 10]
 [14 16 18]]
[[ 6  8 10]
 [14 16 18]]
[[ 6  8 10]
 [14 16 18]]
